### ISSUE TITLE
Documentation incorrectly refers to http://localhost:8124/repo.git, when it should be http://localhost:8124/repo

### ISSUE THREAD

**Issue by vrsean** [dustin/gitmirror#10]
If you try to go to http://localhost:8124/repo.git according to the README, the service will constantly log "Not found" 

Going to http://localhost:8124/repo produces the desired results.

**Comment by vrsean** [comment]
Rather, the documentation should refer to git clone --mirror to produce the git tree.

**Comment by dustin** [comment]
I don't quite see what you're looking at.  The doc references `--mirror`.  I just tried the code from README and it seemed right.

Please reopen if I missed something.

**Comment by vrsean** [comment]
I can't reopen the issue as I'm not a collaborator:

In your README.markdown from https://github.com/dustin/gitmirror

>Now, create a location for your mirrors and (as an example), check out the gitmirror source into it:

>mkdir /tmp/gitmirrors
>cd /tmp/gitmirrors
>git clone git://github.com/dustin/gitmirror

git clone doesn't make a .git mirror and is sorta useless by itself.

```

[root@oceans-ci01-old tmp]# git clone git://github.com/dustin/gitmirror
Cloning into 'gitmirror'...
remote: Counting objects: 263, done.
remote: Total 263 (delta 0), reused 0 (delta 0), pack-reused 263
Receiving objects: 100% (263/263), 48.26 KiB, done.
Resolving deltas: 100% (145/145), done.
[root@oceans-ci01-old tmp]# ls -al gitmirror
total 328
drwxr-xr-x   5 root root   4096 Jun 25 15:58 .
drwxrwxrwt. 69 root root 290816 Jun 25 15:58 ..
drwxr-xr-x   8 root root   4096 Jun 25 15:58 .git
-rw-r--r--   1 root root     37 Jun 25 15:58 .gitignore
-rw-r--r--   1 root root   6929 Jun 25 15:58 gitmirror.go
-rw-r--r--   1 root root    627 Jun 25 15:58 gitmirror_test.go
-rw-r--r--   1 root root   1136 Jun 25 15:58 LICENSE
-rw-r--r--   1 root root   4050 Jun 25 15:58 README.markdown
drwxr-xr-x   2 root root   4096 Jun 25 15:58 setuphooks
drwxr-xr-x   3 root root   4096 Jun 25 15:58 support
[root@oceans-ci01-old tmp]# ls -ald gitmirror
drwxr-xr-x 5 root root 4096 Jun 25 15:58 gitmirror
[root@oceans-ci01-old tmp]# git grep -- --mirror
fatal: Not a git repository (or any of the parent directories): .git
[root@oceans-ci01-old tmp]# cd gitmirror/
[root@oceans-ci01-old gitmirror]# git grep -- --mirror
gitmirror.go:           exec.Command(*git, "clone", "--mirror", "--bare", repo,
[root@oceans-ci01-old gitmirror]# 
```

There's definitely no --mirror in there besides the source.

**Comment by dustin** [comment]
Local edits.  *sigh*

Thanks.

BTW, I recommend not running this stuff as root.  git's already had one vulnerability this would open you up to.  Least priv is best priv.  :)

**Comment by vrsean** [comment]
Oh, no, it runs as its own git user.   That was just a screen dump while I was already logged in on a remote box.
