### ISSUE TITLE
"context canceled" when cloning

### ISSUE THREAD

**Issue by borsboom** [dustin/gitmirror#12]
Using the latest master, I get this error when a Github hook triggers a clone of a new repo:

> 13:43:13.093455 Running [/usr/bin/git clone --mirror --bare git://github.com/haskell-lang/haskell-lang.git /gitmirror/haskell-lang.git] in /tmp
> 13:43:13.093473 Error running [/usr/bin/git clone --mirror --bare git://github.com/haskell-lang/haskell-lang.git /gitmirror/haskell-lang.git] in /tmp:  context canceled

This looks like it was introduced in 9631bce1d13ba59d0118cfecc05def03dfbd0f1a.  When I switched to the previous commit (eff6bf33146ed1c067b3a1fa1f6e1efdb8386a29) this error no longer occurred.

**Comment by dustin** [comment]
Ah, you're doing background syncing, aren't you?  I could see how that could fail.

**Comment by dustin** [comment]
Let me know if this doesn't fix it.

**Comment by borsboom** [comment]
Thanks, that worked!

You seemed surprised that I'd be using background syncing in the GitHub webhook.  Do you recommend against  background syncing for this case?

**Comment by dustin** [comment]
Nope, I think I do the same.  It just hasn't affected me because I hadn't
done any initial clones lately.
