### ISSUE TITLE
How do I clone from the mirror?

### ISSUE THREAD

**Issue by clintmod** [dustin/gitmirror#16]
Hi… thanks for the project!

Might be a super silly question… but I can't figure out how to clone from the local mirror?

I've got gitmirror up and running with ngrok so that anytime I commit to github it updates a local git repository.

How do I clone from local git repo or is that not what this is for? 
Do I need to setup a git daemon to do that?

**Comment by clintmod** [comment]
Yep that was it… have to run git daemon… here's a readonly snippet to share all the mirrors…

`git daemon --base-path=/home/git/repos --export-all --reuseaddr --informative-errors --verbose`

**Comment by dustin** [comment]
You can also serve it via http, but most of the time, I've just mirrored to
local files and cloned from there.
